export const APP_LOAD = "APP_LOAD";

export const ASYNC_START = "ASYNC_START";
export const ASYNC_END = "ASYNC_END";

export const HOME_PAGE_LOADED = "HOME_PAGE_LOADED";
export const HOME_PAGE_UNLOADED = "HOME_PAGE_UNLOADED";

export const CHANGE_ADVERTISER = "CHANGE_ADVERTISER";
export const CHANGE_TIMELINE = "CHANGE_TIMELINE";
